name: MatthewSheriff
favicon: null
layout_spectrum: 0.41144
typography_spectrum: 0.3594979583285749
title: Art Director / Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2edff'
    - '#afb3bc'
    - '#070908'
    - '#1f2a3d'
    - '#4a6c92'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.7354113890323788
purpose: []
